name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Keystore
        run: |
          if [ ! -f signingkey.jks ]; then
            keytool -genkey -v -keystore signingkey.jks -alias komikku -keyalg RSA -keysize 2048 -validity 10000 -storepass "komikku123" -keypass "komikku123" -dname "CN=komikku, OU=komikku, O=komikku, L=Unknown, ST=Unknown, C=Unknown"
            keytool -list -v -keystore signingkey.jks -storepass "komikku123" -alias komikku | grep SHA256 > fingerprint_raw.txt
            cat fingerprint_raw.txt | sed 's/.*SHA256: //' | tr -d ':' | tr '[:upper:]' '[:lower:]' > fingerprint.txt
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add signingkey.jks fingerprint.txt
            git commit -m "Add permanent signing key and fingerprint"
            git push
          else
            echo "signingkey.jks already exists"
          fi
